### ISSUE TITLE
Security Data Issues - Secrets in clear text 

### ISSUE THREAD

**Issue by shaybenb** [MidnightBSD/security-advisory#38]
Hi ,

url : https://github.com/MidnightBSD/security-advisory/blob/5cf125fa1b5c5c9381b2e76b7838550473fb1980/src/main/resources/application.yml

![image](https://user-images.githubusercontent.com/46863888/104613294-c5932900-568f-11eb-8df3-2c34aa21103e.png)

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by laffer1** [comment]
Passwords have been changed. Thanks for reporting this.

**Comment by shaybenb** [comment]
thanks for take our commet ,and prodact your data .

hop that we help you.
